// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8JUGAVyOVNkMlJgAkpKugBixAendCsK8',
    appId: '1:1003261916751:web:7a63fb56c251c38a99dc3a',
    messagingSenderId: '1003261916751',
    projectId: 'plant-care-o1',
    authDomain: 'plant-care-o1.firebaseapp.com',
    storageBucket: 'plant-care-o1.firebasestorage.app',
    measurementId: 'G-VG3NTVZ42K',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDP0G1Qi9b38zSY_sE0u3FgFT7PZ90LItY',
    appId: '1:1003261916751:ios:cb531b36b1acd17a99dc3a',
    messagingSenderId: '1003261916751',
    projectId: 'plant-care-o1',
    storageBucket: 'plant-care-o1.firebasestorage.app',
    iosBundleId: 'com.example.plantDiseaseDetectionMobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDP0G1Qi9b38zSY_sE0u3FgFT7PZ90LItY',
    appId: '1:1003261916751:ios:cb531b36b1acd17a99dc3a',
    messagingSenderId: '1003261916751',
    projectId: 'plant-care-o1',
    storageBucket: 'plant-care-o1.firebasestorage.app',
    iosBundleId: 'com.example.plantDiseaseDetectionMobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8JUGAVyOVNkMlJgAkpKugBixAendCsK8',
    appId: '1:1003261916751:web:20b52943a719829299dc3a',
    messagingSenderId: '1003261916751',
    projectId: 'plant-care-o1',
    authDomain: 'plant-care-o1.firebaseapp.com',
    storageBucket: 'plant-care-o1.firebasestorage.app',
    measurementId: 'G-1SBM07SWLT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyEyBPDC1i7t_yLpIT7ML8pC207A9bmR4',
    appId: '1:1003261916751:android:5df092a89627630899dc3a',
    messagingSenderId: '1003261916751',
    projectId: 'plant-care-o1',
    storageBucket: 'plant-care-o1.firebasestorage.app',
  );
}
